/**
 * Typed access to the generated backend wire types.
 *
 * `generated/schema.d.ts` is GENERATED by openapi-typescript from the vendored OpenAPI snapshot
 * (`src/test/contract/openapi.json`), which is itself a byte copy of the backend's guarded
 * snapshot (`backend/tests/guards/openapi.snapshot.json`). `just contract-refresh` walks that
 * chain; `just contract-check` (also pre-commit and CI) fails when any link is stale. Never
 * hand-edit either file — see docs/api-contract.md.
 *
 * This module is the ONLY reader of `./generated/schema` (ESLint `no-restricted-imports`).
 * Everything else imports from here:
 *
 *   - `Schema<"UserOut">` — a wire schema by name; feature `types/index.ts` files alias these.
 *   - `ApiPath`, `PathsWith`, `RequestBody`, `PathParams`, `QueryParams`, `SuccessBody` — what
 *     the path-typed `apiClient` and the `mockApi` test helper derive their signatures from, so
 *     the path + verb of a call decide its body and result types. There is no free type
 *     parameter anywhere: a wire shape that is not in the spec cannot be spelled.
 */
import type { components, paths } from "./generated/schema";

/** A backend wire schema by name: `Schema<"UserOut">`. */
export type Schema<K extends keyof components["schemas"]> = components["schemas"][K];

/** Every path the backend declares (the `paths` keys of the generated spec). */
export type ApiPath = keyof paths;

/** The verbs the client can issue. */
export type HttpMethod = "get" | "post" | "put" | "patch" | "delete";

/**
 * Paths on which `M` is a declared operation. The generator emits `get?: never` for the verbs a
 * path does not support, which reads back as `undefined` — so "undefined is assignable" means
 * "not an operation". (`src/test/guards/api-types.guard.test.ts` pins this emission.)
 */
export type PathsWith<M extends HttpMethod> = {
  [P in ApiPath]: undefined extends paths[P][M] ? never : P;
}[ApiPath];

/** The `operations[...]` entry behind `M P`. */
type Operation<P extends PathsWith<M>, M extends HttpMethod> = NonNullable<paths[P][M]>;

/** The `application/json` schema inside a requestBody / response entry, else `never`. */
type JsonContent<T> = T extends { content: { "application/json": infer B } } ? B : never;

/** JSON request body of `M P`; `never` when the operation takes none (POST /api/auth/signout). */
export type RequestBody<P extends PathsWith<M>, M extends HttpMethod> =
  Operation<P, M> extends { requestBody?: infer RB } ? JsonContent<RB> : never;

/** `PathsWith<M>` minus the operations that declare a request body (for the bodyless verbs). */
export type BodylessPaths<M extends HttpMethod> = {
  [P in PathsWith<M>]: [RequestBody<P, M>] extends [never] ? P : never;
}[PathsWith<M>];

/** Templated `{segments}` of `P` as an object (`{ organization_id: string }`); `never` when none. */
export type PathParams<P extends PathsWith<M>, M extends HttpMethod> =
  Operation<P, M> extends { parameters: { path?: infer PP } } ? NonNullable<PP> : never;

/** Declared query parameters of `M P`; `never` when the operation declares none. */
export type QueryParams<P extends PathsWith<M>, M extends HttpMethod> =
  Operation<P, M> extends { parameters: { query?: infer Q } } ? NonNullable<Q> : never;

type SuccessStatus = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226;

/** Body of one response entry: its JSON schema, or `undefined` for a body-less (204) entry. */
type ResponseJson<R> = R extends { content: { "application/json": infer B } } ? B : undefined;

/**
 * What a successful `M P` resolves to: the JSON of every 2xx response the operation declares
 * (200 and 201 alike), `undefined` for a 204. Errors are not here — they are thrown as ApiError.
 */
export type SuccessBody<P extends PathsWith<M>, M extends HttpMethod> =
  Operation<P, M> extends { responses: infer R }
    ? { [S in keyof R & SuccessStatus]: ResponseJson<R[S]> }[keyof R & SuccessStatus]
    : never;
